version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      # Install dependencies
      - pip install sphinx furo readthedocs-sphinx-search sphinx-autobuild sphinx-design  sphinx-hoverxref sphinx-inline-tabs sphinx-issues sphinx-notfound-page myst-parser sphinx-rtd-theme

sphinx:
  configuration: docs/source/conf.py